name: "deployment"

on:
  push:
    branches:
      - main

jobs:
    deploy:
      runs-on: ubuntu-latest

      steps:
        - name: Checkout
          uses: actions/checkout@v2

        - name: Setup SSH
          uses: webfactory/ssh-agent@v0.5.0
          with:
            ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

        - name: Install dependencies
          run: npm install

        - name: Tests
          run: npm run test
    docker:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v2
        - name: Setup QEMU
          uses: docker/setup-qemu-action@v2
        - name: Setup Docker Buildx
          uses: docker/setup-buildx-action@v2
        - name: Login to DockerHub
          uses: docker/login-action@v2
          with:
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_PASSWORD }}
        - name: Build and push
          uses: docker/build-push-action@v2
          with:
            push: true
            tags: ${{ secrets.DOCKER_USERNAME }}/nodejs-docker:${{ github.sha }}
            file: ./Dockerfile
        - name:
          uses: appleboy/ssh-action@master
          with:
            host: ${{ secrets.HOST }}
            username: ${{ secrets.USERNAME }}
            key: ${{ secrets.SSH_PRIVATE_KEY }}
            script: |
              docker pull ${{ secrets.DOCKER_USERNAME }}/nodejs-docker:${{ github.sha }}
              docker tag ${{ secrets.DOCKER_USERNAME }}/nodejs-docker:${{ github.sha }} ${{ secrets.DOCKER_USERNAME }}/nodejs-docker:latest
              docker stop nodejs-docker || true
              docker rm nodejs-docker || true
              docker run -d --name nodejs-docker -p 3000:3000 ${{ secrets.DOCKER_USERNAME }}/nodejs-docker:latest
   